/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author ruben
 */

import javax.swing.ImageIcon;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.awt.Image;
import java.io.IOException;

public class CardInstrumento extends javax.swing.JPanel {

    /**
     * Creates new form CardInstrumento
     */
    public CardInstrumento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JLabel();
        Descricao = new javax.swing.JScrollPane();
        AreaDescricao = new javax.swing.JTextArea();
        Botoes = new javax.swing.JPanel();
        BotaoTocar = new javax.swing.JButton();
        BotaoVerMais = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setBackground(new java.awt.Color(11, 27, 58));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 27, 58), 20));
        setPreferredSize(new java.awt.Dimension(1070, 136));

        Nome.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        Nome.setForeground(java.awt.Color.white);
        Nome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Nome.setText("Nome do instrumento");

        Descricao.setBackground(new java.awt.Color(11, 27, 70));
        Descricao.setBorder(null);

        AreaDescricao.setEditable(false);
        AreaDescricao.setBackground(new java.awt.Color(11, 27, 58));
        AreaDescricao.setColumns(20);
        AreaDescricao.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        AreaDescricao.setForeground(java.awt.Color.white);
        AreaDescricao.setLineWrap(true);
        AreaDescricao.setRows(2);
        AreaDescricao.setWrapStyleWord(true);
        AreaDescricao.setBorder(null);
        Descricao.setViewportView(AreaDescricao);

        Botoes.setOpaque(false);

        BotaoTocar.setBackground(new java.awt.Color(253, 255, 255));
        BotaoTocar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        BotaoTocar.setForeground(new java.awt.Color(11, 27, 58));
        BotaoTocar.setText("Tocar Som");
        BotaoTocar.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 5, 7, 5));
        BotaoTocar.setBorderPainted(false);
        BotaoTocar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoTocar.setFocusPainted(false);
        BotaoTocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTocarActionPerformed(evt);
            }
        });

        BotaoVerMais.setBackground(new java.awt.Color(253, 255, 255));
        BotaoVerMais.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        BotaoVerMais.setForeground(new java.awt.Color(11, 27, 58));
        BotaoVerMais.setText("Ver Mais");
        BotaoVerMais.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 5, 7, 5));
        BotaoVerMais.setBorderPainted(false);
        BotaoVerMais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoVerMais.setFocusPainted(false);
        BotaoVerMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVerMaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotoesLayout = new javax.swing.GroupLayout(Botoes);
        Botoes.setLayout(BotoesLayout);
        BotoesLayout.setHorizontalGroup(
            BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoTocar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoVerMais, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addContainerGap())
        );
        BotoesLayout.setVerticalGroup(
            BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoTocar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoVerMais)
                .addContainerGap())
        );

        Imagem.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(Botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Botoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Imagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoTocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTocarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoTocarActionPerformed

    private void BotaoVerMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVerMaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoVerMaisActionPerformed
    
    public void setCardInstrumento(String nome, String descricao, boolean temAudio, String caminhoImagem){
        
        Nome.setText(nome);
        AreaDescricao.setText(descricao);
        BotaoTocar.setEnabled(temAudio);
        
        try{
            BufferedImage imagem = ImageIO.read(getClass().getResource(caminhoImagem));

            Image imagemRedimensionada = imagem.getScaledInstance(100, 100, Image.SCALE_SMOOTH);

            Imagem.setIcon(new ImageIcon(imagemRedimensionada));
            
        } catch (IOException e){
            
            System.out.println(e.getMessage());
        }
    }
    
    public void setCardInstrumento(String nome, String descricao, boolean temAudio){
        
        Nome.setText(nome);
        AreaDescricao.setText(descricao);
        BotaoTocar.setEnabled(temAudio);
        
        try{
            System.out.println(getClass().getResource("/imagens/teste.jpg"));
            BufferedImage imagem = ImageIO.read(getClass().getResource("/imagens/sem_imagem.png"));
        
            Image imagemRedimensionada = imagem.getScaledInstance(100, 100, Image.SCALE_SMOOTH);

            Imagem.setIcon(new ImageIcon(imagemRedimensionada));
            
        } catch (IOException e){
            
            System.out.println(e.getMessage());
        }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaDescricao;
    private javax.swing.JButton BotaoTocar;
    private javax.swing.JButton BotaoVerMais;
    private javax.swing.JPanel Botoes;
    private javax.swing.JScrollPane Descricao;
    private javax.swing.JLabel Imagem;
    private javax.swing.JLabel Nome;
    // End of variables declaration//GEN-END:variables
}
