/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author ruben
 */

import javax.swing.ImageIcon;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.awt.Image;
import java.io.IOException;

public class CardListarPadrao extends javax.swing.JPanel {

    /**
     * Creates new form CardInstrumento
     */
    public CardListarPadrao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JLabel();
        Descricao = new javax.swing.JScrollPane();
        AreaDescricao = new javax.swing.JTextArea();
        Id = new javax.swing.JLabel();

        setBackground(new java.awt.Color(11, 27, 58));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 27, 58), 20));
        setPreferredSize(new java.awt.Dimension(403, 146));

        Nome.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        Nome.setForeground(java.awt.Color.white);
        Nome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Nome.setText("Nome");

        Descricao.setBackground(new java.awt.Color(11, 27, 70));
        Descricao.setBorder(null);

        AreaDescricao.setEditable(false);
        AreaDescricao.setBackground(new java.awt.Color(11, 27, 58));
        AreaDescricao.setColumns(20);
        AreaDescricao.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        AreaDescricao.setForeground(java.awt.Color.white);
        AreaDescricao.setLineWrap(true);
        AreaDescricao.setRows(2);
        AreaDescricao.setWrapStyleWord(true);
        AreaDescricao.setBorder(null);
        Descricao.setViewportView(AreaDescricao);

        Id.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        Id.setForeground(java.awt.Color.white);
        Id.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Id.setText("ID:100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Id))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(Id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void setCard(String nome, String descricao, String id){
        
        Nome.setText(nome);
        AreaDescricao.setText(descricao);
        Id.setText("ID: " + id);
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaDescricao;
    private javax.swing.JScrollPane Descricao;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Nome;
    // End of variables declaration//GEN-END:variables
}
