/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author ruben
 */

import javax.swing.ImageIcon;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.awt.Image;
import java.io.IOException;

public class ConfirmacaoCard extends javax.swing.JPanel {

    /**
     * Creates new form CardInstrumento
     */
    public ConfirmacaoCard(String nome, String descricao, boolean deuCerto) {
        initComponents();
        
        NomeObjeto.setText(nome);
        
        DescricaoObjeto.setText(descricao);
        
        if(deuCerto) Icone.setIcon(new ImageIcon("src/main/resources/imagens/check.png"));
        else Icone.setIcon(new ImageIcon("src/main/resources/imagens/close.png"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DescricaoObjeto = new javax.swing.JLabel();
        NomeObjeto = new javax.swing.JLabel();
        Icone = new javax.swing.JLabel();

        setBackground(new java.awt.Color(11, 27, 58));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 27, 58), 20));
        setPreferredSize(new java.awt.Dimension(290, 311));

        DescricaoObjeto.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        DescricaoObjeto.setForeground(java.awt.Color.white);
        DescricaoObjeto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DescricaoObjeto.setText("Objeto Registrado");

        NomeObjeto.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        NomeObjeto.setForeground(java.awt.Color.white);
        NomeObjeto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeObjeto.setText("Familia_instrumento");

        Icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/check.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DescricaoObjeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Icone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(NomeObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Icone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescricaoObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescricaoObjeto;
    private javax.swing.JLabel Icone;
    private javax.swing.JLabel NomeObjeto;
    // End of variables declaration//GEN-END:variables
}
