/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AudioControl;
import controller.FamiliaInstrumentoControl;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import model.Audio;
import model.FamiliaInstrumento;
import model.Instrumento;
import model.InstrumentoHarmonico;
import model.InstrumentoMelodico;
import model.InstrumentoRitmico;

/**
 *
 * @author ruben
 */
public class InterfaceInstrumentoVerMais extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfaceInstrumentoVerMais.class.getName());
    
    private Long instrumento_id;
    private TelaInstrumentos telaPrincipal;
    
    /**
     * Creates new form InterfaceInputPadrão
     * 
     * @param titulo serve para mostrar o titulo da interface
     */
    public InterfaceInstrumentoVerMais(Instrumento instrumento, TelaInstrumentos telaPrincipal) {
        initComponents();
        
        this.telaPrincipal = telaPrincipal;
        
        this.instrumento_id = instrumento.getId();
        
        if(instrumento.getNome() != null) Nome.setText(instrumento.getNome());
        if(instrumento.getId() != -1) ID.setText("ID: " + String.valueOf(instrumento.getId()));
        
        if(instrumento.getHistoria() != null) InputHistoria.setText(instrumento.getHistoria());
        else InputHistoria.setText("Sem História");
        
        if(instrumento.getDescricao() != null) InputDescricao.setText(instrumento.getDescricao());
        else InputDescricao.setText("Sem Descrição");
            
        if(instrumento instanceof InstrumentoHarmonico) InputTipo.setText("Instrumento Harmônico");
        if(instrumento instanceof InstrumentoRitmico) InputTipo.setText("Instrumento Rítmico");
        if(instrumento instanceof InstrumentoMelodico) InputTipo.setText("Instrumento Melódico");

        FamiliaInstrumentoControl familiaController = new FamiliaInstrumentoControl();
        
        FamiliaInstrumento familiaInstrumento = null;
        
        try{
            if(instrumento.getFamiliaId() != -1) familiaInstrumento = familiaController.listarFamiliaporId(instrumento.getFamiliaId());
            
            if(familiaInstrumento != null){
                
                if(familiaInstrumento.getNome() != null) InputFamilia.setText(familiaInstrumento.getNome());
                
                if(familiaInstrumento.getDescricao() != null) InputDescricaoFamilia.setText(familiaInstrumento.getDescricao());
                else InputDescricaoFamilia.setText("Sem Descrição da Família");
            }
        
        }catch(Exception e){
            
            System.out.println("Erro: " + e.getMessage());
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeErro = new javax.swing.JPopupMenu();
        ErroTextNome = new javax.swing.JMenuItem();
        Tela = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        Historia = new javax.swing.JLabel();
        ScrollHistoria = new javax.swing.JScrollPane();
        InputHistoria = new javax.swing.JTextArea();
        Familia = new javax.swing.JLabel();
        InputFamilia = new javax.swing.JTextField();
        BotaoCancelar = new javax.swing.JButton();
        DescricaoFamilia = new javax.swing.JLabel();
        InputTipo = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        ScrollDescricaoFamilia = new javax.swing.JScrollPane();
        InputDescricaoFamilia = new javax.swing.JTextArea();
        Audio = new javax.swing.JLabel();
        BotaoTocarSom = new javax.swing.JButton();
        Descricao = new javax.swing.JLabel();
        ScrollDescricao = new javax.swing.JScrollPane();
        InputDescricao = new javax.swing.JTextArea();

        NomeErro.setBackground(new java.awt.Color(11, 27, 58));
        NomeErro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NomeErro.setForeground(java.awt.Color.white);
        NomeErro.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        NomeErro.setBorderPainted(false);
        NomeErro.setPreferredSize(new java.awt.Dimension(340, 33));

        ErroTextNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ErroTextNome.setText("Preencha o campo");
        ErroTextNome.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        ErroTextNome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ErroTextNome.setPreferredSize(new java.awt.Dimension(300, 33));
        ErroTextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErroTextNomepadraoActionPerformed(evt);
            }
        });
        NomeErro.add(ErroTextNome);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Tela.setBackground(new java.awt.Color(11, 27, 58));

        Nome.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Nome.setForeground(java.awt.Color.white);
        Nome.setText("Nome");

        Historia.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        Historia.setForeground(java.awt.Color.white);
        Historia.setText("História");
        Historia.setToolTipText("");

        ScrollHistoria.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white, 3));
        ScrollHistoria.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ScrollHistoria.setOpaque(false);
        ScrollHistoria.setPreferredSize(new java.awt.Dimension(610, 78));

        InputHistoria.setBackground(new java.awt.Color(11, 27, 70));
        InputHistoria.setColumns(20);
        InputHistoria.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        InputHistoria.setForeground(java.awt.Color.white);
        InputHistoria.setLineWrap(true);
        InputHistoria.setRows(3);
        InputHistoria.setWrapStyleWord(true);
        InputHistoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        InputHistoria.setCaretColor(java.awt.Color.white);
        InputHistoria.setEnabled(false);
        ScrollHistoria.setViewportView(InputHistoria);

        Familia.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        Familia.setForeground(java.awt.Color.white);
        Familia.setText("Família do Instrumento:");
        Familia.setToolTipText("");

        InputFamilia.setBackground(new java.awt.Color(11, 27, 70));
        InputFamilia.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        InputFamilia.setForeground(java.awt.Color.white);
        InputFamilia.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white, 3));
        InputFamilia.setCaretColor(java.awt.Color.white);
        InputFamilia.setEnabled(false);
        InputFamilia.setPreferredSize(new java.awt.Dimension(64, 52));
        InputFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFamiliaActionPerformed(evt);
            }
        });

        BotaoCancelar.setBackground(new java.awt.Color(252, 255, 255));
        BotaoCancelar.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        BotaoCancelar.setText("Retornar");
        BotaoCancelar.setBorderPainted(false);
        BotaoCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoCancelar.setPreferredSize(new java.awt.Dimension(180, 50));
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });

        DescricaoFamilia.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        DescricaoFamilia.setForeground(java.awt.Color.white);
        DescricaoFamilia.setText("Descrição da Família:");
        DescricaoFamilia.setToolTipText("");

        InputTipo.setBackground(new java.awt.Color(11, 27, 70));
        InputTipo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        InputTipo.setForeground(java.awt.Color.white);
        InputTipo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white, 3));
        InputTipo.setCaretColor(java.awt.Color.white);
        InputTipo.setEnabled(false);
        InputTipo.setPreferredSize(new java.awt.Dimension(64, 52));
        InputTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTipoActionPerformed(evt);
            }
        });

        ID.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        ID.setForeground(java.awt.Color.white);
        ID.setText("ID");

        Tipo.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        Tipo.setForeground(java.awt.Color.white);
        Tipo.setText("Tipo");
        Tipo.setToolTipText("");

        ScrollDescricaoFamilia.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white, 3));
        ScrollDescricaoFamilia.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ScrollDescricaoFamilia.setOpaque(false);
        ScrollDescricaoFamilia.setPreferredSize(new java.awt.Dimension(610, 78));

        InputDescricaoFamilia.setBackground(new java.awt.Color(11, 27, 70));
        InputDescricaoFamilia.setColumns(20);
        InputDescricaoFamilia.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        InputDescricaoFamilia.setForeground(java.awt.Color.white);
        InputDescricaoFamilia.setLineWrap(true);
        InputDescricaoFamilia.setRows(3);
        InputDescricaoFamilia.setWrapStyleWord(true);
        InputDescricaoFamilia.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        InputDescricaoFamilia.setCaretColor(java.awt.Color.white);
        InputDescricaoFamilia.setEnabled(false);
        ScrollDescricaoFamilia.setViewportView(InputDescricaoFamilia);

        Audio.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        Audio.setForeground(java.awt.Color.white);
        Audio.setText("Áudio");
        Audio.setToolTipText("");

        BotaoTocarSom.setBackground(new java.awt.Color(252, 255, 255));
        BotaoTocarSom.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        BotaoTocarSom.setText("Tocar Som");
        BotaoTocarSom.setBorderPainted(false);
        BotaoTocarSom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoTocarSom.setPreferredSize(new java.awt.Dimension(180, 50));
        BotaoTocarSom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTocarSomActionPerformed(evt);
            }
        });

        Descricao.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        Descricao.setForeground(java.awt.Color.white);
        Descricao.setText("Descrição");
        Descricao.setToolTipText("");

        ScrollDescricao.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white, 3));
        ScrollDescricao.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ScrollDescricao.setOpaque(false);
        ScrollDescricao.setPreferredSize(new java.awt.Dimension(610, 78));

        InputDescricao.setBackground(new java.awt.Color(11, 27, 70));
        InputDescricao.setColumns(20);
        InputDescricao.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        InputDescricao.setForeground(java.awt.Color.white);
        InputDescricao.setLineWrap(true);
        InputDescricao.setRows(3);
        InputDescricao.setWrapStyleWord(true);
        InputDescricao.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        InputDescricao.setCaretColor(java.awt.Color.white);
        InputDescricao.setEnabled(false);
        ScrollDescricao.setViewportView(InputDescricao);

        javax.swing.GroupLayout TelaLayout = new javax.swing.GroupLayout(Tela);
        Tela.setLayout(TelaLayout);
        TelaLayout.setHorizontalGroup(
            TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TelaLayout.createSequentialGroup()
                        .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TelaLayout.createSequentialGroup()
                                .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(TelaLayout.createSequentialGroup()
                                    .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Familia)
                                                .addComponent(InputFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ScrollHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Tipo)
                                        .addComponent(InputTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(24, 24, 24)
                                    .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DescricaoFamilia)
                                        .addComponent(ScrollDescricaoFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Audio)
                                        .addComponent(BotaoTocarSom, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ScrollDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(27, 27, 27))
                    .addGroup(TelaLayout.createSequentialGroup()
                        .addComponent(Historia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Descricao)
                        .addGap(361, 361, 361))))
        );
        TelaLayout.setVerticalGroup(
            TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(ID))
                .addGap(46, 46, 46)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Historia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Familia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescricaoFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(InputFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TelaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ScrollDescricaoFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Audio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(BotaoTocarSom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(TelaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InputTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ErroTextNomepadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErroTextNomepadraoActionPerformed
        
    }//GEN-LAST:event_ErroTextNomepadraoActionPerformed

    private void BotaoTocarSomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTocarSomActionPerformed
        AudioControl audioController = new AudioControl();

        try{
            List<Audio> audios = audioController.listarAudio();

            for(Audio a: audios){

                if(!a.getArquivo().equalsIgnoreCase("semArquivo") && a.getInstrumentoID() == instrumento_id){

                    File arquivo = new File(a.getArquivo());

                    AudioInputStream audio = AudioSystem.getAudioInputStream(arquivo);

                    Clip clip = AudioSystem.getClip();

                    clip.open(audio);

                    clip.start();

                    Thread.sleep(clip.getMicrosecondLength() / 1000);
                }
            }

        }catch(UnsupportedAudioFileException e){

            System.out.println("Erro: " + e.getMessage());

        }catch(IOException e){

            System.out.println("Erro: " + e.getMessage());

        }catch(Exception e){

            System.out.println("Erro: " + e.getMessage());

        }
    }//GEN-LAST:event_BotaoTocarSomActionPerformed

    private void InputTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTipoActionPerformed

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed

        this.dispose();

        TelaInstrumentos telaInstrumento = null;

        if(telaPrincipal != null) telaPrincipal.setVisible(true);
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void InputFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFamiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFamiliaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Audio;
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoTocarSom;
    private javax.swing.JLabel Descricao;
    private javax.swing.JLabel DescricaoFamilia;
    private javax.swing.JMenuItem ErroTextNome;
    private javax.swing.JLabel Familia;
    private javax.swing.JLabel Historia;
    private javax.swing.JLabel ID;
    private javax.swing.JTextArea InputDescricao;
    private javax.swing.JTextArea InputDescricaoFamilia;
    private javax.swing.JTextField InputFamilia;
    private javax.swing.JTextArea InputHistoria;
    private javax.swing.JTextField InputTipo;
    private javax.swing.JLabel Nome;
    private javax.swing.JPopupMenu NomeErro;
    private javax.swing.JScrollPane ScrollDescricao;
    private javax.swing.JScrollPane ScrollDescricaoFamilia;
    private javax.swing.JScrollPane ScrollHistoria;
    private javax.swing.JPanel Tela;
    private javax.swing.JLabel Tipo;
    // End of variables declaration//GEN-END:variables
}
