/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.*;
import model.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.border.Border;

/**
 *
 * @author ruben
 */
public class InterfaceAtualizarPadrao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfaceAtualizarPadrao.class.getName());
    
    private boolean unicaTela;
    private TelaInstrumentos telaPrincipal;
    
    private TelaListarPadrao telaListar;
    private String titulo;
    private String especializacao;
    
    Border bordaVermelha = BorderFactory.createLineBorder(Color.RED, 3);
    
    Border bordaBranca = BorderFactory.createLineBorder(Color.WHITE, 3);
    
    /**
     * Creates new form InterfaceDeletarPadrao
     */
    public InterfaceAtualizarPadrao(String titulo, boolean unicaTela, String especializacao, TelaInstrumentos telaPrincipal) {
        initComponents();
        
        this.telaPrincipal = telaPrincipal;
        
        Titulo.setText(titulo);
        
        Erro.setVisible(false);
        
        setLocationRelativeTo(null);
        
        this.unicaTela = unicaTela;
        this.titulo = titulo;
        this.especializacao = especializacao;
        
        SwingUtilities.invokeLater(() -> {
        
            InputID.setBorder(bordaBranca);
            
            InputID.addKeyListener(new KeyAdapter() {
                
                @Override
                public void keyTyped(KeyEvent e){
                    
                    char caractere = e.getKeyChar();
                    
                    if(!Character.isDigit(caractere)){
                        e.consume();
                    }
                }
            });
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tela = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        InputID = new javax.swing.JTextField();
        Erro = new javax.swing.JLabel();
        BotaoCancelar = new javax.swing.JButton();
        BotaoProcurar = new javax.swing.JButton();
        Listar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tela.setBackground(new java.awt.Color(11, 27, 58));
        Tela.setPreferredSize(new java.awt.Dimension(680, 657));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Titulo.setForeground(java.awt.Color.white);
        Titulo.setText("Titulo");

        ID.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        ID.setForeground(java.awt.Color.white);
        ID.setText("ID:");
        ID.setToolTipText("");

        InputID.setBackground(new java.awt.Color(11, 27, 70));
        InputID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        InputID.setForeground(java.awt.Color.white);
        InputID.setBorder(null);
        InputID.setCaretColor(java.awt.Color.white);
        InputID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputIDActionPerformed(evt);
            }
        });

        Erro.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Erro.setForeground(java.awt.Color.white);
        Erro.setText("Erro:");
        Erro.setToolTipText("");

        BotaoCancelar.setBackground(new java.awt.Color(252, 255, 255));
        BotaoCancelar.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        BotaoCancelar.setText("Cancelar");
        BotaoCancelar.setBorderPainted(false);
        BotaoCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoCancelar.setPreferredSize(new java.awt.Dimension(180, 50));
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });

        BotaoProcurar.setBackground(new java.awt.Color(252, 255, 255));
        BotaoProcurar.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        BotaoProcurar.setText("Procurar");
        BotaoProcurar.setBorderPainted(false);
        BotaoProcurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoProcurar.setMaximumSize(new java.awt.Dimension(180, 50));
        BotaoProcurar.setPreferredSize(new java.awt.Dimension(180, 50));
        BotaoProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoProcurarActionPerformed(evt);
            }
        });

        Listar.setBackground(new java.awt.Color(11, 27, 58));
        Listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_32px.png"))); // NOI18N
        Listar.setBorder(null);
        Listar.setBorderPainted(false);
        Listar.setContentAreaFilled(false);
        Listar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Listar.setFocusPainted(false);
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelaLayout = new javax.swing.GroupLayout(Tela);
        Tela.setLayout(TelaLayout);
        TelaLayout.setHorizontalGroup(
            TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TelaLayout.createSequentialGroup()
                        .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Erro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TelaLayout.createSequentialGroup()
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Listar))
                        .addComponent(Titulo)
                        .addComponent(InputID, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        TelaLayout.setVerticalGroup(
            TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Titulo)
                .addGap(35, 35, 35)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Listar))
                .addGap(18, 18, 18)
                .addComponent(InputID, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(Erro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tela, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputIDActionPerformed

    private void BotaoProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoProcurarActionPerformed
        
        
        if(InputID.getText() == null || InputID.getText().isBlank()){
            
            InputID.setBorder(bordaVermelha);
        
        }else{
            
            InputID.setBorder(bordaBranca);
        }
        
        Map<String, Long> retornos = new HashMap<>();
        
        Long ID = Long.parseLong(InputID.getText());
        
        Object dado = null; 
        
        try{
                        
            if(titulo.equalsIgnoreCase("Instrumento")){

                InstrumentosControl instrumentosControl = new InstrumentosControl();

                dado = instrumentosControl.listarInstrumentosporID(ID, especializacao);

            }else if(titulo.equalsIgnoreCase("Audio")){

                AudioControl audioControl = new AudioControl();
                
                dado = audioControl.listarAudioporId(ID);

            }else if(titulo.equalsIgnoreCase("Familia_Instrumento")){

                FamiliaInstrumentoControl familiaInstrumentoControl = new FamiliaInstrumentoControl();
                
                dado = familiaInstrumentoControl.listarFamiliaporId(ID);
                
            }else if(titulo.equalsIgnoreCase("Tecnica")){

                TecnicaControl tecnicaControl = new TecnicaControl();
                
                dado = tecnicaControl.listarTecnicaporId(ID);
                
            }else if(titulo.equalsIgnoreCase("Material")){

                MaterialControl materialControl = new MaterialControl();
                
                dado = materialControl.listarMaterialporID(ID);
                
            }else if(titulo.equalsIgnoreCase("Afinação")){

                AfinacaoControl afinacaoControl = new AfinacaoControl();
                
                dado = afinacaoControl.listarAfinacaoporID(ID);
                
            }
            
            if(dado == null){
                    
                Erro.setText("Não existe um " + titulo + " com esse ID");
                    
                InputID.setBorder(bordaVermelha);
                
                return;
            }
            
        } catch(Exception e){
            
            System.out.println("Erro: " + e.getMessage());
        }
        
        this.dispose();
        
        if(titulo.equalsIgnoreCase("Audio")){
            
            InterfaceInputAudio telaAudio = new InterfaceInputAudio(true, true, dado, telaPrincipal);
            
            telaAudio.setVisible(true);
            
        }else if(titulo.equalsIgnoreCase("Instrumento")){
            
            InterfaceInputInstrumento telaInstrumento = new InterfaceInputInstrumento(especializacao,true, true, dado, telaPrincipal);
            
            telaInstrumento.setVisible(true);

        }else{
            
            InterfaceInputPadrao telaPadrao = new InterfaceInputPadrao(titulo, true, true, dado, telaPrincipal);
            
            telaPadrao.setVisible(true);

        }        
    }//GEN-LAST:event_BotaoProcurarActionPerformed

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        this.dispose();
        
        if(!unicaTela) return;    
        
        if(telaPrincipal != null) telaPrincipal.setVisible(true);
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        if(telaListar != null){
            
            if(!telaListar.isDisplayable()){
                
                telaListar = null;
            
            }else{
                
                return;
            }
        }
        
        try{
            telaListar = new TelaListarPadrao(titulo, especializacao, telaPrincipal);
            
        } catch(Exception e){
            
            System.out.println("Erro: " + e.getMessage());
        }
        
        telaListar.setVisible(true);
    }//GEN-LAST:event_ListarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoProcurar;
    private javax.swing.JLabel Erro;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField InputID;
    private javax.swing.JButton Listar;
    private javax.swing.JPanel Tela;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
