/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ruben
 */

import javax.swing.JMenuItem;

public class TelaListarPadrao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaListarPadrao.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaListarPadrao(String nome) {
        initComponents();
        
        DivInstrumentos.getVerticalScrollBar().setUnitIncrement(32);

        CardsPanel.setLayout(new javax.swing.BoxLayout(CardsPanel, javax.swing.BoxLayout.Y_AXIS));
        
        setLocationRelativeTo(null);
        
        titulo.setText(nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DivPanel = new javax.swing.JPanel();
        DivInstrumentos = new javax.swing.JScrollPane();
        CardsPanel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        BotaoFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(11, 27, 43));

        DivPanel.setBackground(new java.awt.Color(11, 27, 58));

        DivInstrumentos.setBorder(null);
        DivInstrumentos.setAutoscrolls(true);
        DivInstrumentos.setViewportView(CardsPanel);

        CardsPanel.setBackground(new java.awt.Color(11, 27, 78));
        CardsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        CardsPanel.setAutoscrolls(true);
        CardsPanel.setPreferredSize(new java.awt.Dimension(435, 355));

        javax.swing.GroupLayout CardsPanelLayout = new javax.swing.GroupLayout(CardsPanel);
        CardsPanel.setLayout(CardsPanelLayout);
        CardsPanelLayout.setHorizontalGroup(
            CardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        CardsPanelLayout.setVerticalGroup(
            CardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        DivInstrumentos.setViewportView(CardsPanel);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Lista");

        BotaoFechar.setBackground(new java.awt.Color(252, 255, 255));
        BotaoFechar.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        BotaoFechar.setText("Fechar");
        BotaoFechar.setBorderPainted(false);
        BotaoFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoFechar.setPreferredSize(new java.awt.Dimension(180, 50));
        BotaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DivPanelLayout = new javax.swing.GroupLayout(DivPanel);
        DivPanel.setLayout(DivPanelLayout);
        DivPanelLayout.setHorizontalGroup(
            DivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DivPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(DivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BotaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DivInstrumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DivPanelLayout.setVerticalGroup(
            DivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DivPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(DivInstrumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(BotaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DivPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DivPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFecharActionPerformed

        this.dispose();

    }//GEN-LAST:event_BotaoFecharActionPerformed
 
    public void addCard(String nome, String descricao, String id){
        
        CardListarPadrao card = new CardListarPadrao();
        card.setCard(nome, descricao, id);
                
        CardsPanel.add(card);
        CardsPanel.add(javax.swing.Box.createVerticalStrut(15));
        
        CardsPanel.revalidate();
        CardsPanel.repaint();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoFechar;
    private javax.swing.JPanel CardsPanel;
    private javax.swing.JScrollPane DivInstrumentos;
    private javax.swing.JPanel DivPanel;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
