/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ruben
 */

import controller.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;
import model.*;

public class TelaListarPadrao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaListarPadrao.class.getName());
    
    private TelaInstrumentos telaPrincipal;
    
    /**
     * Creates new form TelaPrincipal
     * @param nome é o parametro para definir o nome da Lista e o que ela vai mostrar
     * @param especializacao serve para mostrar a especialização de instrumento
     * @param telaPrincipal é a referencia da primeira tela de Instrumentos
     */
    public TelaListarPadrao(String nome, String especializacao, TelaInstrumentos telaPrincipal) throws Exception{
        initComponents();
        
        this.telaPrincipal = telaPrincipal;
        
        
        //Aumenta a velocidade do scroll da lista
        DivInstrumentos.getVerticalScrollBar().setUnitIncrement(32);

        //Adiciona o layout que permite que o campo se expanda para baixo com o scroll
        CardsPanel.setLayout(new javax.swing.BoxLayout(CardsPanel, javax.swing.BoxLayout.Y_AXIS));
        
        DivInstrumentos.setViewportView(CardsPanel);
        
        // coloca a tela no centro da tela do pc
        setLocationRelativeTo(null);
        
        titulo.setText(nome);
        
        
        //Cadeia de if else if para definir qual tabela os dados devem ser buscados
        if(nome.equalsIgnoreCase("Instrumento")){

            InstrumentosControl instrumentosControl = new InstrumentosControl();
            
            List<Instrumento> instrumentos = new ArrayList<>();
            
            if(especializacao == null || especializacao.equalsIgnoreCase("harmonico"))
                instrumentos.addAll(instrumentosControl.listarInstrumentos("harmonico"));
            
            if(especializacao == null || especializacao.equalsIgnoreCase("melodico"))
                instrumentos.addAll(instrumentosControl.listarInstrumentos("melodico"));
            
            if(especializacao == null || especializacao.equalsIgnoreCase("ritmico"))
                instrumentos.addAll(instrumentosControl.listarInstrumentos("ritmico"));
            
            for(Instrumento i: instrumentos){
                
                this.addCard(i.getNome(), i.getDescricao(), String.valueOf(i.getId()));
            }

        }else if(nome.equalsIgnoreCase("Audio")){

            AudioControl audioControl = new AudioControl();
                
            List<Audio> audios = audioControl.listarAudio();
            
            for(Audio a: audios){
                
                this.addCard(a.getTitulo(), a.getDescricao(), String.valueOf(a.getId()));
            }

        }else if(nome.equalsIgnoreCase("Familia_Instrumento")){

            FamiliaInstrumentoControl familiaInstrumentoControl = new FamiliaInstrumentoControl();
                
            List<FamiliaInstrumento> familias = familiaInstrumentoControl.listarFamilia();
            
            for(FamiliaInstrumento fi: familias){
                
                this.addCard(fi.getNome(), fi.getDescricao(), String.valueOf(fi.getId()));
            }
            
        }else if(nome.equalsIgnoreCase("Tecnica")){

            TecnicaControl tecnicaControl = new TecnicaControl();
                
            List<Tecnica> tecnicas = tecnicaControl.listarTecnicas();

            for(Tecnica t: tecnicas){
                
                this.addCard(t.getNome(), t.getDescricao(), String.valueOf(t.getId()));
            }
            
        }else if(nome.equalsIgnoreCase("Material")){

            MaterialControl materialControl = new MaterialControl();
                
            List<Material> materiais = materialControl.listarMaterial();

            for(Material m: materiais){
                
                this.addCard(m.getNome(), m.getDescricao(), String.valueOf((int)m.getId()));
            }
            
        }else if(nome.equalsIgnoreCase("Afinação")){

            AfinacaoControl afinacaoControl = new AfinacaoControl();
                
            List<Afinacao> afinacoes = afinacaoControl.listarAfinacao();

            for(Afinacao a: afinacoes){
                
                this.addCard(a.getNome(), a.getDescricao(), String.valueOf(a.getId()));
            }
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DivPanel = new javax.swing.JPanel();
        DivInstrumentos = new javax.swing.JScrollPane();
        CardsPanel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        BotaoFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(11, 27, 43));

        DivPanel.setBackground(new java.awt.Color(11, 27, 58));

        DivInstrumentos.setBorder(null);
        DivInstrumentos.setAutoscrolls(true);
        DivInstrumentos.setViewportView(CardsPanel);

        CardsPanel.setBackground(new java.awt.Color(11, 27, 78));
        CardsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        CardsPanel.setAutoscrolls(true);
        CardsPanel.setPreferredSize(null);

        javax.swing.GroupLayout CardsPanelLayout = new javax.swing.GroupLayout(CardsPanel);
        CardsPanel.setLayout(CardsPanelLayout);
        CardsPanelLayout.setHorizontalGroup(
            CardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        CardsPanelLayout.setVerticalGroup(
            CardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        DivInstrumentos.setViewportView(CardsPanel);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Lista");

        BotaoFechar.setBackground(new java.awt.Color(252, 255, 255));
        BotaoFechar.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        BotaoFechar.setText("Fechar");
        BotaoFechar.setBorderPainted(false);
        BotaoFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoFechar.setPreferredSize(new java.awt.Dimension(180, 50));
        BotaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DivPanelLayout = new javax.swing.GroupLayout(DivPanel);
        DivPanel.setLayout(DivPanelLayout);
        DivPanelLayout.setHorizontalGroup(
            DivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DivPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(DivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(DivInstrumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DivPanelLayout.createSequentialGroup()
                            .addGap(278, 278, 278)
                            .addComponent(BotaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DivPanelLayout.setVerticalGroup(
            DivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DivPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(DivInstrumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(BotaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DivPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DivPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFecharActionPerformed

        //fecha a tela atual
        this.dispose();

    }//GEN-LAST:event_BotaoFecharActionPerformed
 
    
    // Cria os cards com as informações de cada elemento para ser adicionado no campo do scroll
    public final void addCard(String nome, String descricao, String id){
        
        CardListarPadrao card = new CardListarPadrao();
        card.setCard(nome, descricao, id);
        
        CardsPanel.add(card);
        CardsPanel.add(javax.swing.Box.createVerticalStrut(15));
        
        CardsPanel.revalidate();
        CardsPanel.repaint();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoFechar;
    private javax.swing.JPanel CardsPanel;
    private javax.swing.JScrollPane DivInstrumentos;
    private javax.swing.JPanel DivPanel;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
