/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ruben
 */
public class TelaInstrumentos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInstrumentos.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaInstrumentos() {
        initComponents();
        
        DivInstrumentos.getVerticalScrollBar().setUnitIncrement(32);

        CardsPanel.setLayout(new javax.swing.BoxLayout(CardsPanel, javax.swing.BoxLayout.Y_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPopupMenu();
        instrumento = new javax.swing.JMenuItem();
        audio = new javax.swing.JMenuItem();
        familia_instrumento = new javax.swing.JMenuItem();
        tecnica = new javax.swing.JMenuItem();
        material = new javax.swing.JMenuItem();
        parte = new javax.swing.JMenuItem();
        afinação = new javax.swing.JMenuItem();
        DivPanel = new javax.swing.JPanel();
        DivInstrumentos = new javax.swing.JScrollPane();
        CardsPanel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        adicionar = new javax.swing.JButton();
        deletar = new javax.swing.JButton();

        menu.setBackground(new java.awt.Color(11, 27, 58));
        menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu.setForeground(java.awt.Color.white);
        menu.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        menu.setBorderPainted(false);

        instrumento.setBackground(new java.awt.Color(11, 27, 58));
        instrumento.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        instrumento.setForeground(java.awt.Color.white);
        instrumento.setText("instrumento");
        instrumento.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        instrumento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.add(instrumento);

        audio.setBackground(new java.awt.Color(11, 27, 58));
        audio.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        audio.setForeground(java.awt.Color.white);
        audio.setText("audio");
        audio.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        audio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.add(audio);

        familia_instrumento.setBackground(new java.awt.Color(11, 27, 58));
        familia_instrumento.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        familia_instrumento.setForeground(java.awt.Color.white);
        familia_instrumento.setText("familia_instrumento");
        familia_instrumento.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        familia_instrumento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.add(familia_instrumento);

        tecnica.setBackground(new java.awt.Color(11, 27, 58));
        tecnica.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tecnica.setForeground(java.awt.Color.white);
        tecnica.setText("tecnica");
        tecnica.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        tecnica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.add(tecnica);

        material.setBackground(new java.awt.Color(11, 27, 58));
        material.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        material.setForeground(java.awt.Color.white);
        material.setText("material");
        material.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        material.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.add(material);

        parte.setBackground(new java.awt.Color(11, 27, 58));
        parte.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        parte.setForeground(java.awt.Color.white);
        parte.setText("parte");
        parte.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        parte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.add(parte);

        afinação.setBackground(new java.awt.Color(11, 27, 58));
        afinação.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        afinação.setForeground(java.awt.Color.white);
        afinação.setText("afinação");
        afinação.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        afinação.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.add(afinação);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(11, 27, 43));

        DivPanel.setBackground(new java.awt.Color(11, 27, 58));

        DivInstrumentos.setBorder(null);
        DivInstrumentos.setAutoscrolls(true);
        DivInstrumentos.setViewportView(CardsPanel);

        CardsPanel.setBackground(new java.awt.Color(11, 27, 78));
        CardsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        CardsPanel.setAutoscrolls(true);

        javax.swing.GroupLayout CardsPanelLayout = new javax.swing.GroupLayout(CardsPanel);
        CardsPanel.setLayout(CardsPanelLayout);
        CardsPanelLayout.setHorizontalGroup(
            CardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1122, Short.MAX_VALUE)
        );
        CardsPanelLayout.setVerticalGroup(
            CardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        DivInstrumentos.setViewportView(CardsPanel);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Lista de Instrumentos");

        editar.setBackground(new java.awt.Color(11, 27, 58));
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit.png"))); // NOI18N
        editar.setBorder(null);
        editar.setBorderPainted(false);
        editar.setContentAreaFilled(false);
        editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editar.setFocusPainted(false);

        adicionar.setBackground(new java.awt.Color(11, 27, 58));
        adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        adicionar.setBorder(null);
        adicionar.setBorderPainted(false);
        adicionar.setContentAreaFilled(false);
        adicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adicionar.setFocusPainted(false);
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });

        deletar.setBackground(new java.awt.Color(11, 27, 58));
        deletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        deletar.setBorder(null);
        deletar.setBorderPainted(false);
        deletar.setContentAreaFilled(false);
        deletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletar.setFocusPainted(false);

        javax.swing.GroupLayout DivPanelLayout = new javax.swing.GroupLayout(DivPanel);
        DivPanel.setLayout(DivPanelLayout);
        DivPanelLayout.setHorizontalGroup(
            DivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DivPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 465, Short.MAX_VALUE)
                .addComponent(adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(DivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DivPanelLayout.createSequentialGroup()
                    .addContainerGap(42, Short.MAX_VALUE)
                    .addComponent(DivInstrumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 1152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36)))
        );
        DivPanelLayout.setVerticalGroup(
            DivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DivPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(DivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addGroup(DivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(549, Short.MAX_VALUE))
            .addGroup(DivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DivPanelLayout.createSequentialGroup()
                    .addContainerGap(124, Short.MAX_VALUE)
                    .addComponent(DivInstrumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DivPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DivPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        
        menu.show(adicionar, -(adicionar.getWidth()), adicionar.getHeight());
    }//GEN-LAST:event_adicionarActionPerformed
 
    public void addInstrumentoCard(String nome, String descricao, boolean temAudio){
        
        CardInstrumento card = new CardInstrumento();
        card.setCardInstrumento(nome, descricao, temAudio);
                
        CardsPanel.add(card);
        CardsPanel.add(javax.swing.Box.createVerticalStrut(15));
        
        CardsPanel.revalidate();
        CardsPanel.repaint();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardsPanel;
    private javax.swing.JScrollPane DivInstrumentos;
    private javax.swing.JPanel DivPanel;
    private javax.swing.JButton adicionar;
    private javax.swing.JMenuItem afinação;
    private javax.swing.JMenuItem audio;
    private javax.swing.JButton deletar;
    private javax.swing.JButton editar;
    private javax.swing.JMenuItem familia_instrumento;
    private javax.swing.JMenuItem instrumento;
    private javax.swing.JMenuItem material;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JMenuItem parte;
    private javax.swing.JMenuItem tecnica;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
